<?php if ( ! defined('BASE')) exit('Acceso directo prohibido');

class db extends active_record
{
    
    var $query;
    var $queries = array();
    var $counter = 0;
    var $time    = 0;
    var $result  = null;

    private static $instance; 
    
    function __construct($db = null)
    {
        self::$instance = $this;

        $db = (is_null($db)) ? config::getInstance()->load('db')->get_group('config') : $db;  

        foreach ($db as $key => $val)
        {
            $this->$key = $val;            
        }

        $this->_connect();
    }  
    
    
    function __destruct()
    {
        $this->_close();
    }     
    
    public static function getInstance() 
    { 
        if ( ! self::$instance) 
        { 
            self::$instance = new db(); 
        } 
        return self::$instance; 
    }

    function query($query = '')
    {                        
        $query = empty($query) ? $this->get_sql() : $query;     

        $res             = new results();   
        $res->conn_id    = $this->conn_id;
        $res->results_id = $this->_execute($query);

        return $res;
    }    

    function get_queries()
    {
        return $this->queries;        
    }

    function count_queries()
    {
        return $this->counter;
    }
    
    function time_queries()
    {
        return $this->time;
    }   

    function resource()
    {
        return $this->rows;
    }
            
    function last_id()
    {
        return mysql_insert_id();
    }    
    
    function affected_rows()
    {
        return mysql_affected_rows();
    }
    
    private function _execute($query){
        
        $this->counter   += 1;            
        $start_time       = microtime();
        $rows             = mysql_query($query);
        $end_time         = microtime(); 
        $this->queries[]  = $query;
        $this->time      += $end_time - $start_time;           
        $this->query_time = $end_time - $start_time;        
        $this->_query_error();
        
        return $rows;
    }
    
    function total_time()
    {
        return $this->time;
    }

    private function _connect()
    {       
        $this->conn_id = mysql_connect($this->hostname, $this->username, $this->password);
        mysql_query("SET NAMES 'utf8'");
        mysql_select_db ($this->database);
        return $this;
    } 
        
    private function _close()
    {
        mysql_close($this->conn_id);
        return $this;
    }
    
    private function _query_error()
    {
        $error = $this->_error();

        if ($error AND item('dbdebug'))
        {            
            $error_html = '<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;background:#fff;width:600px;">

                            <h3>Error de MySQL</h3>
                            
                            <p>Query: <br />' . nl2br(end($this->queries)) .'</p>
                            <p>Error: '  . $error. '</p>
                            <p>Tiempo: ' . $this->query_time . '</p>

                          </div>';

            echo $error_html;
        }

        return $this;
    }

    function last_query()
    {
        return  '<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;background:#fff;width:600px;">

                    <h3>Último Query</h3>
                    
                    <p>Query: <br />' . nl2br(end($this->queries)).'</p>
                    
                    <p>Tiempo: ' . $this->query_time . '</p>
                                        
                  </div>'; 
    }

    private function _error()
    {
        return mysql_error();
    }

    function escape_str($str, $dashes = FALSE)    
    {   
        if (is_array($str))
        {
            foreach ($str as $key => $val)
            {
                $str[$key] = $this->escape_str($val, $like);
            }        
            return $str;
        }

        if (function_exists('mysql_real_escape_string') AND is_resource($this->conn_id))
        {
            $str = mysql_real_escape_string($str, $this->conn_id);
        }
        elseif (function_exists('mysql_escape_string'))
        {
            $str = mysql_escape_string($str);
        }
        else
        {
            $str = addslashes($str);
        }

        if ($dashes === TRUE)
        {
            if (substr_count($str,'--') > 0)
            {
                $str = str_replace('--', '', $str);
            }
            
            if (substr_count($str, ';')  > 0)
            {
                $str = str_replace(';', '', $str);
            }       
        }        
        return $str;
    }
    


}