<?php
/**
* Nombre de la carpeta donde se encuentra la aplicacion, si se quiere guardarla en otra carpeta
* se crea la carpeta o se cambia el nombre con la estructura establecida.
*/
$application_folder = 'application';

/**
* Constantes base del sistema, extension, rutas al core, al sistema y a la carpeta del framework
* ademas define la constante BASE para comprobar que se haya ingresado mediante este archivo 
* y no directamente.
*/
define('BASE'        , 1);
define('PATH'        , dirname(__FILE__));
define('RUTA_SISTEMA', PATH . '/system');
define('RUTA_CORE'   , RUTA_SISTEMA . '/core/');
define('EXT'         , '.phtml');

/**
* Incluye las librerias del core del framework.
*/

include(RUTA_CORE    . 'constants'      . EXT);
include(RUTA_PACKAGES. 'debug/debug'    . EXT);
include(RUTA_CORE    . 'config'         . EXT);
include(RUTA_CORE    . 'loader'         . EXT);
include(RUTA_CORE    . 'router'         . EXT);
include(RUTA_CORE    . 'language'       . EXT);
include(RUTA_DB      . 'active_record'  . EXT);
include(RUTA_DB      . 'db'             . EXT);
include(RUTA_DB      . 'results'        . EXT);

/**
* Se instancian objetos, el objeto Loader va a autocargar las librerias y helpers definidos en el archivo de 
* configuracion. 
*/

$config = config::getInstance();
$load   = loader::getInstance();

$config->load('config, autoload');
$load->helper($config->get('helpers'));
$load->library($config->get('libraries'));

/**
* Si se quiere se puede reemplazar el set_error_handler() por cualquier handler de errores, ya sea
* error_reporting(E_ALL) o el que se quiera.
*/
if ($config->get('debug'))
{
	set_error_handler("error_handler");
}
else
{
	error_reporting(0);
}

/**
* Se procesa la URI, las rutas y se define si lo que se esta llamando existe, si pasa de la funcion
* $router->get_controller() es porque la URI solicitada existe en alguna parte y ahora solo resta 
* inlcuir y llamar.
*/
$router      = router::getInstance();
$uri         = uri::getInstance();
$controlador = $router->get_controller();

//Si llega hasta acá es porque el controlador existe en alguna parte.
include($controlador->archivo);

$clase = $controlador->controlador;

$load->controlador = $controlador->controlador;

/**
* Por si depronto la clase llega con un slash, se revienta, se coge lo necesario
* para evitar conflictos, problemas o cualquier cosa rara que no este prevista...
*/

if (strpos($clase, '/'))
{
    list($vacio, $clase) = explode('/', $clase);
}

/**
* En algunos puntos como el las configuraciones, archivos de lenguage y en general cualquier
* archivo propio de cada modulo es necesario tener en algun punto el folder del archivo al que
* se esta llamando.
*/
list($config->folder, $dump) = explode('controllers/', $router->controller_file);

$clase = ucwords($clase);
$clase = new $clase;

if (method_exists($clase, $controlador->metodo) && is_callable(array($clase,$controlador->metodo)))
{       
    $vars = ($controlador->directorio == '') ? array_slice($uri->rsegments, 2) : array_slice($uri->rsegments, 3);

    // Funcion que se ejecuta antes de la funcion solicitada.
    if (method_exists($clase, 'before'))
    {
        call_user_func_array(array(&$clase, 'before'), $vars);    
    }

    call_user_func_array(array(&$clase, $controlador->metodo), $vars);   
    
    // Funcion que se ejecuta despues de la funcion solicitada.
    if (method_exists($clase, 'after'))
    {
        call_user_func_array(array(&$clase, 'after'), $vars);    
    }           
}
else
{
    mostrar_error();
}

/* Fin del archivo index.phtml */