<?php 

class template{
	
	private $title;
	private $submenu;
	private $section_title;
	private $section;
	private $content;
	var $menu = TRUE;

	function __construct()
	{
		$template = config::getInstance()->load('template')->get_group('template');
		
		foreach ($template as $key => $val)
		{
			$this->$key = $val;
		}
		
		$this->load = loader::getInstance();		
	}

	function set_title($title = '')
	{
		$this->title = ($title == '') ? $this->config->title : $title;
		return $this;
	}

	function get_title()
	{
		return $this->title;		
	}

	function set_section_title($section_title = '')
	{
		$this->section_title = $section_title;
		return $this;
	}

	function get_section_title()
	{
		return $this->section_title;
	}

	function set_submenu($submenu = '')
	{
		if ($submenu == '')
		{
			return;	
		}

		$this->submenu = $submenu;
		return $this;		
	}

	function get_submenu()
	{
		if ( ! empty($this->submenu)) 
		{
			return "<div id='secondary-menu-wrapper'>
          					{$this->submenu}
        			   </div>";
		}

		return;
	}

	function set_section($section = '')
	{
		if ($section == '')
		{
			return;			
		}
		
		$this->section = $section;
		return $this;
	}

	function get_section()
	{
		if ( ! empty($this->section))
		{
			return "<td id='col-right'>
                	{$this->section}
            		</td>";
		}

		return;
	}

	function get_copyright()
	{
		return $this->copyright;
	}

	function set_content($content = '')
	{
		if ($content == '')
		{
			return;			
		}	

		$this->content = $content;
		return $this;
	}

	function get_content()
	{
		return $this->content;
	}

	function menu($menu = TRUE)
	{
		$this->menu = $menu;
		return $this;
	}

	function render($data = array(), $return = FALSE)
	{

		if ( ! empty($this->content))
		{
        	$this->content = $this->load->view($this->content, $data, TRUE);
        } 

		if ( ! empty($this->submenu))
		{
        	$this->submenu = $this->load->view($this->submenu, $data, TRUE);
        }

        if ( ! empty($this->section))
		{
        	$this->section = $this->load->view($this->section, $data, TRUE);
        }

		$this->load->view($this->template, $data, $return);
	}

}