<?php if ( ! defined('BASE')) die();

/**
 * @author JuanPablo
 * Clase controller
 * clase para extender desde un controlador hijo
 */
class Controller{

  private static $instance; 
    
  public static function getInstance()
  {
      if ( ! self::$instance)
      {
          self::$instance = new Controller();
      }
      return self::$instance;
  }
	/**
	 * Inicia objetos y librerias para 
	 * la clase hija.
	 * 
	 * @return void
	 */
	function __construct()
	{
      
      self::$instance = $this;

      $this->load = loader::getInstance();

      $this->db   = db::getInstance();

      foreach ($this->load->objects as $key => $val)
      {
          if ( ! isset($this->$key))
          {
              $this->$key = $val;
          }
      }

      $this->session  = session::getInstance();
      $this->language = language::getInstance();
      $this->config   = config::getInstance();
      
      if (isset($this->language))
      {
         $this->language->load($this->session->get('user_lang'));
      }

      $this->_register_autoload();
      //show(__CLASS__ . ' iniciada <br>');
	}

  private function _register_autoload()
  {    
      spl_autoload_register(array($this->load, 'autoload_model'));    
  }


	   
}
/* End of file controller.phtml */