<?php if ( ! defined('BASE')) die();//Script para evitar el acceso directo por url

/**
 * @author JuanPablo
 * Clase controller
 * clase para extender desde un controlador hijo
 */
class Controller{

  private static $instance; 
    
  public static function getInstance()
  {
      if ( ! self::$instance)
      {
          self::$instance = new Controller();
      }
      return self::$instance;
  }
	/**
	 * Inicia objetos y librerias para 
	 * la clase hija.
	 * 
	 * @return void
	 */
	public function __construct()
	{
	   self::$instance = $this;

       $this->load = loader::getInstance();
       $this->db   = db::getInstance();

       foreach ($this->load->objects as $key => $val)
       {
           if ( ! isset($this->$key))
           {
            $this->$key = $val;
           }
       }
       
       $this->session  = session::getInstance();
       $this->language = language::getInstance();
       
       if (isset($this->language))
       {
           $this->language->load($this->session->get('user_lang'));
       }
	}
	
	public static function instance()
	{
	   return self::$instance;
	}
	
	   
}
/* End of file controller.phtml */