<?php if ( ! defined('BASE')) exit('Acceso directo prohibido');

/**
 * Clase URI para el manejo de los parametros que entran por la URI.
 *
 */
class Uri{

    private static $instance;
    private $uri_string;
    private $segments;
    private $fetch_uri;
    var $rsegments = array();

    /**
     * Retorna el objeto que se instancia la primera vez, asi se evita crear basura con los objetos
     * @return uri
     */
    public static function getInstance()
    {
        if ( ! self::$instance)
        {
            self::$instance = new Uri;
        }
        return self::$instance;
    }
    
    function __construct()
    {
        self::$instance = $this;

        $input    = input::getInstance();
        $security = security::getInstance();
        $config   = config::getInstance();
        
        $host  = $config->get('base_url');
        $index = $config->get('index_page');
        

        $segments = explode('/', str_replace('/' . $index,'', $input->server('REQUEST_URI',TRUE)));  
                
        foreach ($segments as $key => $val)
        {
          $this->rsegments[] = $security->xss_clean($val);
        }

        return $this;
    }
    
    function get($param = NULL)
    {       
        if (is_null($param))
        {
            return $this->get_uri_string();
        }
     
        return (isset($this->rsegments[$param])) ? $this->rsegments[$param] : '';
    }
    
    
    function fetch_uri()
    {
        if ( ! $this->fetch_uri)
        {
            $this->fetch_uri = $this->rsegments;
        }
        return $this->fetch_uri;
    }
    
    function get_uri_string()
    {
        if ( ! $this->uri_string)
        {
            $this->uri_string = implode('/',$this->rsegments);
        }
        return $this->uri_string;
    }

}