<?php 

/**
 * Muestra un error creado en la clase error.
 *
 * @access  public
 * @param   string
 * @return  string
 */

if( ! function_exists('mostrar_error'))
{ 
    function mostrar_error($mostrar = '404')
    {
        $error = error::getInstance();
        $error->trigger_error($mostrar);
        exit;
    }
}
/**
 * Muestra los errores con estilos
 *
 * @access  public
 * @param   string
 * @return  string
 */

if( ! function_exists('error_handler'))
{ 
    function error_handler($errno, $errstr, $errfile, $errline)
    {
        $levels = array(
                        E_ERROR             =>  'Error',
                        E_WARNING           =>  'Warning',
                        E_PARSE             =>  'Parsing Error',
                        E_NOTICE            =>  'Notice',
                        E_CORE_ERROR        =>  'Core Error',
                        E_CORE_WARNING      =>  'Core Warning',
                        E_COMPILE_ERROR     =>  'Compile Error',
                        E_COMPILE_WARNING   =>  'Compile Warning',
                        E_USER_ERROR        =>  'User Error',
                        E_USER_WARNING      =>  'User Warning',
                        E_USER_NOTICE       =>  'User Notice',
                        E_STRICT            =>  'Runtime Notice'
                    );
    
        echo '<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;background:#fff;width:600px;">

                <h3>A PHP Error was encountered</h3>
                
                <p>Severity: ' . $levels[$errno] .'</p>
                <p>Message: '  . $errstr . '</p>
                <p>Filename: ' . $errfile .'</p>
                <p>Line Number: ' . $errline .'</p>
                
              </div>';
        return TRUE;    
    }
}