<?php 
/* 
 * Configuracion de las rutas del sistema
 * 
 * Es posible configurar rutas de cualquier forma, ejemplo: 
 * 
 * Ruta real
 *  
 *  /controlador/metodo/variables/
 *  
 *   o si esta dentro de una carpeta
 * 
 *  /carpeta/controlador/metodo/variables/
 *  
 * 
 * $route['ruta_del_navegador'] = 'ruta_real';
 * 
 * (:numero) significa que puede va a llegar un numero en el segmento de la uri
 * (:letra) significa que llegara una cadena alfanumerica
 * 
 * Con el signo $ se identifica donde se va a ubicar el reemplazo que se haga y el numero que lo
 * acompaña indica, de izquierda a derecha, el indice del reemplazo, si se tienen (:numero)/(:letra)
 * donde se reemplaza (:numero) sera $1 y donde se reemplaza (:letra) será $2 por ejemplo: 
 * 
 * uri entrante = 'controlador/2/3'
 * 
 * $route['controlador/(:numero)/(:numero)'] = 'controlador/index/$1/$2'
 * 
 * $1 = 2 
 * $2 = 3
 * 
 * daria como resultado
 * 
 * controlador/index/2/3 
 * 
 */
$route['([a-z_]+)/(:numero)/([a-z_]+)/(:numero)'] = '$1/$3/$2/$4';
$route['([a-z_]+)/(:numero)/([a-z_]+)']           = '$1/$3/$2';
$route['([a-z_]+)/(:numero)']                     = '$1/index/$2';
/*
$route['projects/(:numero)/([a-z_]+)']           = 'projects/$2/$1';
$route['messages/(:numero)/([a-z_]+)/(:numero)'] = 'messages/$2/$1/$3';
$route['messages/(:numero)/([a-z_]+)']           = 'messages/$2/$1';
$route['messages/(:numero)']                     = 'messages/index/$1';
*/